server:
  port: 9091
  servlet:
    session:
      cookie:
        name: DEMOSESSION

# sso　认证配置
oauth2-server: http://localhost:9090

security:
  oauth2:
    client:
      grant-type: password    # 授权模式
      client-id: client_1        # 在oauth 服务端注册的client-id
      client-secret: 123456     # 在oauth 服务端注册的secret
      scope: all
      access-token-uri: http://localhost:9090/oauth/token    #获取token 地址
      user-authorization-uri: http://localhost:9090/oauth/authorize  # 认证地址
    resource:
#      filter-order: 3
#      preferTokenInfo: true
      token-info-uri: http://localhost:9090/oauth/check_token  # 检查token
      user-info-uri: http://localhost:9090/oauth/me   # 用户信息
#      jwt:
#        key-uri: ${oauth2-server}/oauth/token_key
    sso:
      login-path: /login
