server:
  servlet:
    context-path: /blog
    session:
      cookie:
        name: BLOG-SESSION

spring:
  profiles:
    active: dev

security:
  oauth2:
    client:
      access-token-uri: ${security.oauth2.server}/oauth/token    #获取token 地址
      user-authorization-uri: ${security.oauth2.server}/oauth/authorize  # 认证地址
    resource:
      preferTokenInfo: true
      token-info-uri: ${security.oauth2.server}/oauth/check_token  # 检查token
      user-info-uri: ${security.oauth2.server}/user/info   # 用户信息

logging:
  level:
    fun.imcoder.cloud.blog.mapper: debug