server:
  servlet:
    context-path: /auth
    session:
      cookie:
        name: AUTH-SESSION

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    fun.imcoder.cloud.auth.mapper: debug
