server:
  port: 9090
  host: localhost
  servlet:
    session:
      cookie:
        name: AUTHSESSION

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imcoder?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

  redis:
     open: true # 是否开启redis缓存  true开启   false关闭
     database: 1
     host: 127.0.0.1
     port: 6379
     timeout: 5000  # 连接超时时长（毫秒）

mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    fun.imcoder.cloud.auth.mapper: debug
