server:
  port: 8100
  host: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3335/imcoder?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root@3335

  redis:
     open: true # 是否开启redis缓存  true开启   false关闭
     database: 1
     host: 47.96.184.62
     port: 6379
     password: ocreatech@2018
     timeout: 5000  # 连接超时时长（毫秒）
